name: Op-Centric Queues Regression Tests

on:
  push:
    branches:
      - main

jobs:
  sim:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup-verilator
        uses: veryl-lang/setup-verilator@v1

      - name: Build and run all tests
        run: |
          cd test
          mkdir -p build
          cd build
          cmake ..
          make check
